pr:
  branches:
    exclude:
      - main
  paths:
    include:
      - /*

pool:
  name: 'selfhosted'


jobs:
- job:
  displayName: 'branch build'
  steps: 
    - script: |
        file_array=$(find . -type f -name "*.bicep" -or -name "*.bicepparam")
        for file in $file_array
        do
          echo "Linting $file"
          az bicep lint -f $file
        done
      displayName: 'lint'
