pr:
  branches:
    exclude:
      - main
  paths:
    include:
      - /*

pool:
  name: 'selfhosted'


jobs:
- job:
  displayName: 'branch build'
  steps: 
    - script: |
        find . -type f -name "*.bicep" -or -name "*.bicepparam"
        # az bicep lint -f ./main.bicepparam
      displayName: 'lint'
