pr:
  branches:
    exclude:
      - main
  paths:
    include:
      - /*

pool:
  name: 'selfhosted'

variables:
  azureServiceConnection: 'id-sub'
  location: 'swedencentral'
  csmParametersFile: './main.bicepparam'


jobs:
- job:
  displayName: 'branch build'
  steps:
    - script: |
        file_array=$(find . -type f -name "*.bicep" -or -name "*.bicepparam")
        for file in $file_array
        do
          echo "Linting $file"
          az bicep lint -f $file
        done
      displayName: 'lint'
    - task: AzureCLI@2
      displayName: 'Priflight validation'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment mg create --management-group-id '7d8e621a-3561-4cc4-9ee6-f03bc8610835' --parameters ./main.bicepparam -l swedencentral -deploymentMode validation
