name: 'Subscription Vending'

# Trigger pipeline on changes to main branch in specified paths
trigger:
  branches:
    include:
      - main

# Parameters section
parameters:
  - name: azureServiceConnection
    type: string
    default: 'id-sub' 

# variables:
#   location: 'swedencentral'
#   csmParametersFile: './main.bicepparam'
#   deploymentScope: 'subscription'
#   deploymentName: 'tuttu-billingscope-iac'

pool:
  name: 'selfhosted'

jobs:
- job: 
  displayName: 'Subscription Vending'
  steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment mg create --management-group-id '7d8e621a-3561-4cc4-9ee6-f03bc8610835' --parameters ./main.bicepparam -l swedencentral 
