name: 'Subscription Vending'

# Trigger pipeline on changes to main branch in specified paths
trigger:
  branches:
    include:
      - main

# Parameters section
parameters:
  - name: azureServiceConnection
    type: string
    default: 'tuttu-billingscope-sc-nonprod-01' # Define your Azure service connection here

variables:
  location: 'swedencentral'
  csmParametersFile: './main.bicepparam'
  deploymentScope: 'subscription'
  deploymentName: 'tuttu-billingscope-iac'

pool:
  name: 'selfhostedvm'

jobs:
- job: 
  displayName: 'Subscription Vending'
  steps:
    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: azureServiceConnection
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az deployment tenant create -n $(deploymentName) -l $(location) --parameters $(csmParametersFile)
